### ISSUE TITLE
建议增加一个 短信验证码登录的方式

### ISSUE THREAD

**Issue by mjyhj** [Zy143L/jd_cookie#1]
这样的话，可以不需要同网络，用验证码登录来获取CK

**Comment by Zy143L** [comment]
> 这样的话，可以不需要同网络，用验证码登录来获取CK

mj老熟人了 你有短信登录的接口么

**Comment by mjyhj** [comment]
> > 这样的话，可以不需要同网络，用验证码登录来获取CK
> 
> mj老熟人了 你有短信登录的接口么

卧槽，有个现成的，打包好EXE的。你看看

**Comment by Zy143L** [comment]
> > > 这样的话，可以不需要同网络，用验证码登录来获取CK
> > 
> > 
> > mj老熟人了 你有短信登录的接口么
> 
> 卧槽，有个现成的，打包好EXE的。你看看
> https://github.com/curtinlv/JD-Script/tree/main/getJDCookie

selenium写的..我对selenium不是很感冒 一回儿看看京东的风控 能用request实现就不上selenium了

**Comment by mjyhj** [comment]
> > > > 这样的话，可以不需要同网络，用验证码登录来获取CK
> > > 
> > > 
> > > mj老熟人了 你有短信登录的接口么
> > 
> > 
> > 卧槽，有个现成的，打包好EXE的。你看看
> > https://github.com/curtinlv/JD-Script/tree/main/getJDCookie
> 
> selenium写的..我对selenium不是很感冒 一回儿看看京东的风控 能用request实现就不上selenium了

你那个日本字名，找不出来，干
