### ISSUE TITLE
 Token 无效，请退出重试

### ISSUE THREAD

**Issue by creazy412** [Zy143L/jd_cookie#12]
![Uploading 京东扫码-token 无效.png…]()

**Comment by creazy412** [comment]
这是下载下来的 exe 文件；用代码跑的获取没问题

**Comment by Zy143L** [comment]
你这个图炸了。。

**Comment by creazy412** [comment]
> 你这个图炸了。。

啥个意思呢

**Comment by creazy412** [comment]
https://gitee.com/creazy1101/blog-image/raw/master/tmp/%E4%BA%AC%E4%B8%9C%E6%89%AB%E7%A0%81-token%20%E6%97%A0%E6%95%88.png

洗把脸才明白什么意思。。。

**Comment by parakai** [comment]
一样的错

**Comment by Zy143L** [comment]
> https://gitee.com/creazy1101/blog-image/raw/master/tmp/%E4%BA%AC%E4%B8%9C%E6%89%AB%E7%A0%81-token%20%E6%97%A0%E6%95%88.png
> 
> 洗把脸才明白什么意思。。。

下最新版本的..你这个是老版本的了

**Comment by Zy143L** [comment]
> 一样的错

你看看版本是不是V1.2

**Comment by creazy412** [comment]
可以了，v1.2 没问题
ps：v1.2 的60秒倒计时是真让人捉急，建议弄个3分钟
