### ISSUE TITLE
不知道为什么老出错？

### ISSUE THREAD

**Issue by b08240** [Zy143L/jd_cookie#15]
![1](https://user-images.githubusercontent.com/52618121/128227349-2e9ab8be-da37-4080-a81e-07593a726a0e.png)
如图，以前1.0一直好好的，1.2和1.3老是出这种错误，必须得赶在出错前扫码并登录才可以，否则稍微迟一点就会出这种错误

**Comment by Zy143L** [comment]
我的锅...马上修

**Comment by Zy143L** [comment]
https://github.com/Zy143L/jd_cookie/releases/
