### ISSUE TITLE
报错No module named 'requests'

### ISSUE THREAD

**Issue by ycyfff** [Zy143L/jd_cookie#2]
## 开始执行... 2021-06-28 08:57:10

Traceback (most recent call last):
  File "raw_jd_ck.py", line 3, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

## 执行结束... 2021-06-28 08:57:10  耗时 0 秒

**Comment by Zy143L** [comment]
什么面板呢 居然没有requests模块..

**Comment by DollyDino99** [comment]
pip install  requests

**Comment by Zy143L** [comment]
> pip install requests

如果是青龙的话 需要pip3

**Comment by DollyDino99** [comment]
> > pip install requests
> 
> 如果是青龙的话 需要pip3

确实是

**Comment by ycyfff** [comment]
pip3 install requests，多谢，已解决
