### ISSUE TITLE
青龙的ql raw并没有更新

### ISSUE THREAD

**Issue by Lovelearningxi** [Zy143L/jd_cookie#20]
## 开始执行... 2021-08-24 22:33:33

Ver: 1.2.2 By: limoe 面板专用版本
https://github.com/Zy143L/jd_cookie
JD扫码获取Cookie
请手动复制链接到在线二维码生成网站,并扫码登录

https://plogin.m.jd.com/cgi-bin/m/tmauth?client_type=m&appid=300&token=

**Comment by Zy143L** [comment]
已更新
