### ISSUE TITLE
后缀不同账号无法区分

### ISSUE THREAD

**Issue by chyaww** [Zy143L/jd_cookie#28]
我有两个前面一样，后面多了一个数字的账号，如abc和abc1，运行脚本后日志如下：

pt_pin=abc 检索成功

pt_pin=abc1 状态正常

pt_pin=abc 账号有效
--------------------

pt_pin=abc1 检索成功

pt_pin=abc1 状态正常

pt_pin=abc1 账号有效

然后也不会转换成cookie添加到环境变量。

**Comment by Zy143L** [comment]
..加到bug清单了 在修了 在修了
