### ISSUE TITLE
win10专业版执行提示生成二维码失败

### ISSUE THREAD

**Issue by JoeNik** [Zy143L/jd_cookie#3]
如果系统未弹出二维码图片, 请手动生成二维码
URL地址已复制到剪切板, 请使用在线二维码生成
https://plogin.m.jd.com/cgi-bin/m/tmauth?client_type=m&appid=300&token=m_tokenAAEAIF-rkhtaBY4Ryh1qvuo80paYfF-UFI7aIFq1X_2laBtw
二维码生成失败, 请手动在线生成
https://plogin.m.jd.com/cgi-bin/m/tmauth?client_type=m&appid=300&token=m_tokenAAEAIF-rkhtaBY4Ryh1qvuo80paYfF-UFI7aIFq1X_2laBtw

**Comment by Zy143L** [comment]
?

**Comment by JoeNik** [comment]
二维码生成失败。要咋解决呢

**Comment by Zy143L** [comment]
如果系统未弹出二维码图片, 请手动生成二维码
URL地址已复制到剪切板, 请使用在线二维码生成
上面写的清清楚楚的...你自己复制链接 去在线生成二维码的地方
这个报错 你电脑上没装看图软件?

**Comment by JoeNik** [comment]
哦。确实没装。自带的看图不行是吗，那我下载一个试试

**Comment by Zy143L** [comment]
自带看图可以 但是估计你没设置为默认看图软件

**Comment by JoeNik** [comment]
依赖里面好像少了这个
pip3 install pillow
我安装完是可以了

**Comment by Zy143L** [comment]
你是下的源码版本吧? 我侧面有放打包好的..

**Comment by JoeNik** [comment]
是啊我用的源码。
