### ISSUE TITLE
面板显示问题

### ISSUE THREAD

**Issue by DollyDino99** [Zy143L/jd_cookie#4]
佬，啥时候可以出面板带二维码的脚本，运行完看日志复制链接时，日志在动，不好操作，只能进入日志栏才是静止可复制，手机操作的话会更麻烦一点

**Comment by Zy143L** [comment]
晚些时间

**Comment by DollyDino99** [comment]
> 晚些时间

好的，明白  另外佬的tg账号有吗，我从用了你的面板后没找到联系方式

**Comment by Zy143L** [comment]
有问题直接发issues就行了 看到会处理的

**Comment by DollyDino99** [comment]
> 有问题直接发issues就行了 看到会处理的

好的，明白
