### ISSUE TITLE
在复制链接去草料之类生成二维码图片的基础上，增加直接输出2维码图片链接的能力。

### ISSUE THREAD

**Issue by linsongze** [Zy143L/jd_cookie#5]
payload = {'data': qrurl}
    result = urlencode(payload, quote_via=quote_plus)
    logger.info('https://api.qrserver.com/v1/create-qr-code/?size=300x300&{0}'.format(result))

**Comment by Zy143L** [comment]
多谢 我去测试下

**Comment by linsongze** [comment]
我在fork的分支加了，测试ok,也可以合并 pr

**Comment by Zy143L** [comment]
> 我在fork的分支加了，测试ok,也可以合并 pr

你提交pr吧 如果有其他可以改的地方 欢迎
