### ISSUE TITLE
py版本运行不了

### ISSUE THREAD

**Issue by xukf2000** [Zy143L/jd_cookie#7]
![image](https://user-images.githubusercontent.com/34463908/123909224-45e1e800-d9ab-11eb-8d2f-4cad3913ad18.png)
![image](https://user-images.githubusercontent.com/34463908/123909297-5db96c00-d9ab-11eb-9c2d-c9b7d030926c.png)
缺少什么模块

exe在win7上还无法执行，闪退

**Comment by Zy143L** [comment]
缺什么模块..他已经告诉你了
No module named pyperclip.
