### ISSUE TITLE
windows11 不弹二维码

### ISSUE THREAD

**Issue by SummerSec** [Zy143L/jd_cookie#9]
![image](https://user-images.githubusercontent.com/47944478/125181409-07fc8380-e237-11eb-9ddc-5befb296a780.png)

**Comment by Zy143L** [comment]
建议检查网络..Win11Dev测试正常
看看电脑是不是开了什么代理软件

**Comment by SummerSec** [comment]
网络正常，windows11 最新版，第二个推送版
